# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7LJa_vmJSwRmnAMBC3mSKKPDiwn4AtX
"""

import math


def addition(a, b):
    return a + b


def subtraction(a, b):
    return a - b


def multiplication(a, b):
    return a * b


def division(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b


def power(a, b):
    return a ** b


def modulus(a, b):
    if b == 0:
        return "Cannot perform modulus with zero"
    return a % b


def factorial(n):
    if n < 0:
        return "Factorial not defined for negative numbers"
    return math.factorial(n)


def square_root(n):
    if n < 0:
        return "Square root not defined for negative numbers"
    return math.sqrt(n)


# Main Program
while True:
    print("\n------ Advanced Calculator ------")
    print("1 Addition")
    print("2 Subtraction")
    print("3 Multiplication")
    print("4 Division")
    print("5 Power")
    print("6 Modulus")
    print("7 Factorial")
    print("8 Square Root")
    print("9 Exit")

    try:
        choice = int(input("Enter choice: "))

        if choice == 9:
            print("Program terminated")
            break

        elif choice in [1, 2, 3, 4, 5, 6]:
            a = float(input("Enter first number: "))
            b = float(input("Enter second number: "))

            if choice == 1:
                print("Result =", addition(a, b))
            elif choice == 2:
                print("Result =", subtraction(a, b))
            elif choice == 3:
                print("Result =", multiplication(a, b))
            elif choice == 4:
                print("Result =", division(a, b))
            elif choice == 5:
                print("Result =", power(a, b))
            elif choice == 6:
                print("Result =", modulus(a, b))

        elif choice == 7:
            n = int(input("Enter number: "))
            print("Factorial =", factorial(n))

        elif choice == 8:
            n = float(input("Enter number: "))
            print("Square Root =", square_root(n))

        else:
            print("Invalid choice. Try again.")

    except ValueError:
        print("Invalid numeric input. Try again.")

def classify_temperature(temp):
    if temp < 18:
        return "Cold"
    elif temp > 28:
        return "Hot"
    else:
        return "Normal"


def calculate_statistics(readings):
    avg_temp = sum(readings) / len(readings)
    highest = max(readings)
    lowest = min(readings)
    return avg_temp, highest, lowest


def display_report(avg, highest, lowest, counts):
    print("\nTemperature Summary")
    print("Average Temperature =", round(avg, 2))
    print("Highest Temperature =", highest)
    print("Lowest Temperature =", lowest)

    print("\nCondition Count")
    print("Hot =", counts["Hot"])
    print("Normal =", counts["Normal"])
    print("Cold =", counts["Cold"])

    print("\nSuggested Action")
    if counts["Hot"] > 0:
        print("Fan ON")
    if counts["Cold"] > 0:
        print("Heater ON")
    if counts["Hot"] == 0 and counts["Cold"] == 0:
        print("No action required")


# Main Program
print("Temperature Monitoring System")

n = int(input("Enter number of readings: "))

readings = []
counts = {"Hot": 0, "Normal": 0, "Cold": 0}

for i in range(n):
    temp = float(input("Enter temperature: "))
    readings.append(temp)

    condition = classify_temperature(temp)
    counts[condition] += 1

avg, highest, lowest = calculate_statistics(readings)

display_report(avg, highest, lowest, counts)