# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149B59CP9tma-12hFrsMY2KY6IAw1SJ-k
"""

def classify_temperature(temp):
    if temp < 18:
        return "Cold"
    elif temp > 28:
        return "Hot"
    else:
        return "Normal"


def calculate_statistics(readings):
    avg_temp = sum(readings) / len(readings)
    highest = max(readings)
    lowest = min(readings)
    return avg_temp, highest, lowest


def display_report(avg, highest, lowest, counts):
    print("\nTemperature Summary")
    print("Average Temperature =", round(avg, 2))
    print("Highest Temperature =", highest)
    print("Lowest Temperature =", lowest)

    print("\nCondition Count")
    print("Hot =", counts["Hot"])
    print("Normal =", counts["Normal"])
    print("Cold =", counts["Cold"])

    print("\nSuggested Action")
    if counts["Hot"] > 0:
        print("Fan ON")
    if counts["Cold"] > 0:
        print("Heater ON")
    if counts["Hot"] == 0 and counts["Cold"] == 0:
        print("No action required")


# Main Program
print("Temperature Monitoring System")

n = int(input("Enter number of readings: "))

readings = []
counts = {"Hot": 0, "Normal": 0, "Cold": 0}

for i in range(n):
    temp = float(input("Enter temperature: "))
    readings.append(temp)

    condition = classify_temperature(temp)
    counts[condition] += 1

avg, highest, lowest = calculate_statistics(readings)

display_report(avg, highest, lowest, counts)